/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserList {
  docs?: UserInList[];
  page?: number;
  limit?: number;
  total?: number;
  maxPage?: number;
  [k: string]: unknown;
}
export interface UserInList {
  id?: string;
  firstname?: string;
  lastname?: string;
  email?: string;
  phone?: string;
  avatar?: string;
  [k: string]: unknown;
}
